### ISSUE TITLE
Crash on interacting with Villager to trade for Mod-Items

### ISSUE THREAD

**Issue by Jeserkon** [SongXia-NYU/nuclear_craft#15]
I tried to trade with do Villiger but my Game crashed in Singleplayer

The Crashreport:
---- Minecraft Crash Report ----
// You're mean.

Time: 5/27/21 4:14 PM
Description: Unexpected error

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_51] {}
	at com.song.nuclear_craft.villagers.RandomTradeBuilder.lambda$createFunction$6(RandomTradeBuilder.java:183) ~[?:1.16.5] {re:classloading}
	at com.song.nuclear_craft.villagers.RandomTradeBuilder$$Lambda$6831/519875075.apply(Unknown Source) ~[?:?] {}
	at com.song.nuclear_craft.villagers.RandomTradeBuilder.lambda$build$5(RandomTradeBuilder.java:178) ~[?:1.16.5] {re:classloading}
	at com.song.nuclear_craft.villagers.RandomTradeBuilder$$Lambda$6832/121372725.func_221182_a(Unknown Source) ~[?:?] {}
	at net.minecraft.entity.merchant.villager.AbstractVillagerEntity.func_213717_a(AbstractVillagerEntity.java:235) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_213712_ef(VillagerEntity.java:765) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.AbstractVillagerEntity.func_213706_dY(AbstractVillagerEntity.java:99) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_230254_b_(VillagerEntity.java:249) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_184230_a(MobEntity.java:1049) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:940) ~[?:?] {re:classloading,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.PlayerController.func_187097_a(PlayerController.java:364) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1351) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$448/1053856141.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_51] {}
	at com.song.nuclear_craft.villagers.RandomTradeBuilder.lambda$createFunction$6(RandomTradeBuilder.java:183) ~[?:1.16.5] {re:classloading}
	at com.song.nuclear_craft.villagers.RandomTradeBuilder$$Lambda$6831/519875075.apply(Unknown Source) ~[?:?] {}
	at com.song.nuclear_craft.villagers.RandomTradeBuilder.lambda$build$5(RandomTradeBuilder.java:178) ~[?:1.16.5] {re:classloading}
	at com.song.nuclear_craft.villagers.RandomTradeBuilder$$Lambda$6832/121372725.func_221182_a(Unknown Source) ~[?:?] {}
	at net.minecraft.entity.merchant.villager.AbstractVillagerEntity.func_213717_a(AbstractVillagerEntity.java:235) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_213712_ef(VillagerEntity.java:765) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.AbstractVillagerEntity.func_213706_dY(AbstractVillagerEntity.java:99) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_230254_b_(VillagerEntity.java:249) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_184230_a(MobEntity.java:1049) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:940) ~[?:?] {re:classloading,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.PlayerController.func_187097_a(PlayerController.java:364) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1351) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Jeserkon'/211, l='ClientLevel', x=-14.93, y=72.00, z=18.61]]
	Chunk stats: Client Chunk Cache: 841, 550
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,63,-5), Chunk: (at 0,3,11 in -2,-1; contains blocks -32,0,-16 to -17,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1506 game time, 1506 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$448/1053856141.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 532263552 bytes (507 MB) / 3915907072 bytes (3734 MB) up to 8619819008 bytes (8220 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9248m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.16.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.16
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.16-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		nuclear_craft-1.16.5-0.8.1.jar                    |Nuclear Craft                 |nuclear_craft                 |1                   |DONE      |NOSIGNATURE
		zombiehorsespawn_1.16.5-2.7.jar                   |Zombie Horse Spawn            |zombiehorsespawn              |2.7                 |DONE      |NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |DONE      |NOSIGNATURE
		randommobeffects_1.16.5-1.2.jar                   |Random Mob Effects            |randommobeffects              |1.2                 |DONE      |NOSIGNATURE
		camoucreeper-2.0.0.jar                            |Camouflaged Creepers          |camoucreepers                 |1.16.5-2.0.0        |DONE      |NOSIGNATURE
		ava-1.7.4.jar                                     |A.V.A - Alliance of Valiant Ar|ava                           |1.7.4               |DONE      |NOSIGNATURE
		giantspawn_1.16.5-2.4.jar                         |Giant Spawn                   |giantspawn                    |2.4                 |DONE      |NOSIGNATURE
		jei-1.16.5-7.6.4.90.jar                           |Just Enough Items             |jei                           |7.6.4.90            |DONE      |NOSIGNATURE
		spookarms-1.0.0.8.jar                             |Spooky Arms                   |spookyarms                    |1.0.0.8             |DONE      |NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |NOSIGNATURE
		xplosives-1.1.jar                                 |XPlosives                     |xplosives                     |1.1.0               |DONE      |NOSIGNATURE
		naturallychargedcreepers_1.16.5-1.4.jar           |Naturally Charged Creepers    |naturallychargedcreepers      |1.4                 |DONE      |NOSIGNATURE
		collective-1.16.5-2.26.jar                        |Collective                    |collective                    |2.26                |DONE      |NOSIGNATURE
		mobsunscreen-1.16.5-3.0.4.jar                     |Mob Sunscreen                 |mobsunscreen                  |1.16.5-3.0.4        |DONE      |NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |DONE      |NOSIGNATURE
		configured-0.4.2-1.16.3.jar                       |Configured                    |configured                    |0.4.2               |DONE      |NOSIGNATURE
		hiddennames-1.16.5-1.1.0.jar                      |Hidden Names                  |hiddennames                   |1.16.5-1.1.0        |DONE      |NOSIGNATURE
		champions-forge-1.16.5-2.0.1.7.jar                |Champions                     |champions                     |1.16.5-2.0.1.7      |DONE      |NOSIGNATURE
		obfuscate-0.6.1-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.1               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |DONE      |NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		Bookshelf-1.16.5-10.0.8.jar                       |Bookshelf                     |bookshelf                     |10.0.8              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		EnchantmentDescriptions-1.16.5-7.0.8.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.8               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		grapple_hooks-1.2.2-33.jar                        |Grapple Hooks                 |grapple_hooks                 |1.2.2-33            |DONE      |NOSIGNATURE
		furniture-7.0.0-pre20-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre20         |DONE      |NOSIGNATURE
		architectury-1.15.13-forge.jar                    |Architectury                  |architectury                  |1.15.13             |DONE      |NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |DONE      |NOSIGNATURE
		AdvancedExplosives-1.16.x-R6.jar                  |Advanced Explosives           |advanced_explosives           |6.0                 |DONE      |NOSIGNATURE
		skeletonhorsespawn_1.16.5-1.6.jar                 |Skeleton Horse Spawn          |skeletonhorsespawn            |1.6                 |DONE      |NOSIGNATURE
		kotlin_libraries-1.0-6.jar                        |Kotlin Libraries              |kotlin_libraries              |1.0-6               |DONE      |NOSIGNATURE
		catalogue-1.1.0-1.16.5.jar                        |Catalogue                     |catalogue                     |1.1.0               |DONE      |NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.18.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.18            |DONE      |NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.304.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.304           |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.16-universal.jar                |Forge                         |forge                         |36.1.16             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		controllable-0.13.1-1.16.3.jar                    |Controllable                  |controllable                  |0.13.1              |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		toyguns-0.1-1.16.4.jar                            |Mr Pineapple's Toy Gun Mod Add|toyguns                       |0.1                 |DONE      |NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |DONE      |NOSIGNATURE
	Crash Report UUID: f1e24270-2146-4ac3-89a7-4593279b6b4d
	Launched Version: forge-36.1.16
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.47, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources
	Current Language: Deutsch (Deutschland)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz

**Comment by Jeserkon** [comment]
It is fixed now
